### ISSUE TITLE
User login system does not play a role

### ISSUE THREAD

**Issue by voctot** [danny-avila/chatgpt-clone#217]
I set the user login system according to your document, which can not work。
/api/.env
```
##########################
# Server configuration:
##########################

# The server will listen to localhost:3080 by default. You can change the target IP as you want.
# If you want to make this server available externally, for example to share the server with others
# or expose this from a Docker container, set host to 0.0.0.0 or your external IP interface.
# Tips: Setting host to 0.0.0.0 means listening on all interfaces. It's not a real IP.
# Use localhost:port rather than 0.0.0.0:port to access the server.
# Set Node env to development if running in dev mode.
HOST=localhost
PORT=3080
NODE_ENV=production

# Change this to proxy any API request.
# It's useful if your machine has difficulty calling the original API server.
# PROXY=

# Change this to your MongoDB URI if different. I recommend appending chatgpt-clone.
MONGO_URI=mongodb://127.0.0.1:27017/chatgpt-clone

##########################
# OpenAI Endpoint:
##########################

# Access key from OpenAI platform.
# Leave it blank to disable this feature.
OPENAI_KEY=

# Identify the available models, separated by commas *without spaces*.
# The first will be default.
# Leave it blank to use internal settings.
OPENAI_MODELS=gpt-3.5-turbo,gpt-3.5-turbo-0301,text-davinci-003,gpt-4

# Reverse proxy settings for OpenAI:
# https://github.com/waylaidwanderer/node-chatgpt-api#using-a-reverse-proxy
# OPENAI_REVERSE_PROXY=

##########################
# BingAI Endpoint:
##########################

# Also used for Sydney and jailbreak

# BingAI Tokens: the "_U" cookies value from bing.com
# Set to "user_provided" to allow the user to provide its token from the UI.
# Leave it blank to disable this endpoint.
BINGAI_TOKEN="user_provided"

# BingAI Host:
# Necessary for some people in different countries, e.g. China (https://cn.bing.com)
# Leave it blank to use default server.
# BINGAI_HOST=https://cn.bing.com

##########################
# ChatGPT Endpoint:
##########################

# ChatGPT Browser Client (free but use at your own risk)
# Access token from https://chat.openai.com/api/auth/session
# Exposes your access token to `CHATGPT_REVERSE_PROXY`
# Set to "user_provided" to allow the user to provide its token from the UI.
# Leave it blank to disable this endpoint
CHATGPT_TOKEN="user_provided"

# Identify the available models, separated by commas. The first will be default.
# Leave it blank to use internal settings.
CHATGPT_MODELS=text-davinci-002-render-sha,text-davinci-002-render-paid,gpt-4

# Reverse proxy settings for ChatGPT
# https://github.com/waylaidwanderer/node-chatgpt-api#using-a-reverse-proxy
# By default, the server will use the node-chatgpt-api recommended proxy (a third party server).
# CHATGPT_REVERSE_PROXY=

##########################
# Search:
##########################

# ENABLING SEARCH MESSAGES/CONVOS
# Requires the installation of the free self-hosted Meilisearch or a paid Remote Plan (Remote not tested)
# The easiest setup for this is through docker-compose, which takes care of it for you.
SEARCH=false

# REQUIRED FOR SEARCH: MeiliSearch Host, mainly for the API server to connect to the search server.
# Replace '0.0.0.0' with 'meilisearch' if serving MeiliSearch with docker-compose.
MEILI_HOST=http://0.0.0.0:7700

# REQUIRED FOR SEARCH: MeiliSearch HTTP Address, mainly for docker-compose to expose the search server.
# Replace '0.0.0.0' with 'meilisearch' if serving MeiliSearch with docker-compose.
MEILI_HTTP_ADDR=0.0.0.0:7700

# REQUIRED FOR SEARCH: In production env., a secure key is needed. You can generate your own.
# This master key must be at least 16 bytes, composed of valid UTF-8 characters.
# MeiliSearch will throw an error and refuse to launch if no master key is provided,
# or if it is under 16 bytes. MeiliSearch will suggest a secure autogenerated master key.
# Using docker, it seems recognized as production so use a secure key.
# This is a ready made secure key for docker-compose, you can replace it with your own.
MEILI_MASTER_KEY=DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt

##########################
# User System:
##########################

# Google:
# Add your Google Client ID and Secret here, you must register an app with Google Cloud to get these values
# https://cloud.google.com/
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=/oauth/google/callback

#JWT:
JWT_SECRET_DEV=secret

# Add a secure secret for production if deploying to live domain.
JWT_SECRET_PROD=secret

# Set the expiration delay for the secure cookie with the JWT token
# Delay is in millisecond e.g. 7 days is 1000*60*60*24*7
SESSION_EXPIRY=1000 * 60 * 60 * 24 * 7

# Site URLs:
# Don't forget to set Node env to development in the Server configuration section above
# if you want to run in dev mode
CLIENT_URL_DEV=http://localhost:3090
SERVER_URL_DEV=http://localhost:3080

# Change these values to domain if deploying:
CLIENT_URL_PROD=http://localhost:3080
SERVER_URL_PROD=http://localhost:3080
```
/client/.env

```
###########################
# Server URL configuration:
###########################

# The social login domain uses this to redirect to localhost:3080 when you run the app in dev mode with Vite.
# Use your domain name as the Prod URL when you deploy the app to a live domain.
# Please note that:
# Social login features will not work if you run the build version on port 3080 locally after modifying the Prod URL
VITE_SERVER_URL_DEV=http://localhost:3080
VITE_SERVER_URL_PROD=http://localhost:3080

# Enable Social Login
# This enables/disables the Login with Google button on the login page.
# Set to true if you have registered the app with google cloud services
# and have set the GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in the /api/.env file
VITE_SHOW_GOOGLE_LOGIN_OPTION=false
```

> Am I the wrong configuration?

**Comment by voctot** [comment]
> Hi @voctot,
> 
> Thank you for reaching out to us. I'm sorry to hear that the user login system is not working as expected. I would like to get more information to help resolve the issue.
> 
> 
> 
> Based on the information you provided, it seems that the user login system was set up according to our document, but is not working. However, I am unable to understand the specific issue that you are facing. Could you please provide more details about the error message or behaviour you are seeing when trying to use the login system?
> 
> 
> 
> Also, can you confirm that the .env file you shared is the correct and complete file? If possible, could you provide a screenshot of the error message or any other details that might help me understand the issue better?
> 
> 
> 
> Once I receive the additional information, I will work on identifying the root cause of the issue and provide you with a resolution.
> 
> 
> 
> Best regards,
> 
> David (Developer & Sponsor)

I can't provide error information because it runs without errors. When I started it with docker, I went directly to the home page and was not intercepted by login.

**Comment by voctot** [comment]
> > I can't provide error information because it runs without errors. When I started it with docker, I went directly to the home page and was not intercepted by login.
> 
> Can you share your docker-compose file? Also pull latest before trying again, the docker image had not been updated with the user system update, and I've also set to build from local as default.

Here is my docker-compose file
```
version: "3.4"

services:
  # client:
  #   image: nginx-client
  #   build:
  #     context: .
  #     target: nginx-client
  #   restart: always
  #   ports:
  #     - 3080:80
  #   volumes:
  #     - /client/node_modules
  #   depends_on:
  #     - api
  api:
    container_name: chat-clone
    ports:
      - 3080:3080               # Change it to 9000:3080 to use nginx
    depends_on:
      - mongodb
    # image: node-api            # Uncomment this to build from local file
    # build:
    #   context: .
    #   target: node-api
    image: chatgptclone/app:0.3.3 # Comment this & uncomment above to build from local file
    restart: always
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      # - CHATGPT_REVERSE_PROXY=http://host.docker.internal:8080/api/conversation # if you are hosting your own chatgpt reverse proxy
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /client/node_modules
      - ./api:/api
      - /api/node_modules
  mongodb:
    container_name: chat-mongodb
    ports:
      - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    env_file:
      - ./api/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - ./meili_data:/meili_data

```
